##
## Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
## Creation Date: Mon Aug 10 16:06:48 PDT 2015
## Last Modified: Sat Jul 25 16:51:51 CEST 2026
## Syntax:        GNU Makefile
## Filename:      Makefile.programs
## vim:           ts=3
##
## Description: Makefile to compile programs using the humlib library.
##
## To run this makefile, type (without quotes) "make -f Makefile.programs",
## (or "gmake -f Makefile.programs" on FreeBSD computers). However this makefile
## is intended to be used with the file "Makefile" which runs this makefile with
## the command "make programs".  The program executables will be placed
## in the "bin" directory.
##
## Without arguments or with the argument "all", this makefile will
## compile all programs.  If you give a program name as an argument, it
## will compile just that program. E.g.: "make -f Makefile.programs flipper"
## or used in conjunction with "Makefile", type "make flipper", which will
## compile the cli/flipper.cpp program and place it in the ./bin directory.
##

# Set the environmental variable $MACOSX_DEPLOYMENT_TARGET to
# "10.9" in Apple OS X to compile for OS X 10.9 and later.
ENV =
ifeq ($(shell uname),Darwin)
   ENV = MACOSX_DEPLOYMENT_TARGET=10.9
   #ARCH = -m32 -arch i386
else
   # ARCH = -m32
endif


###########################################################################
#                                                                         #
# Beginning of user-modifiable configuration variables                    #
#                                                                         #

INCDIR    = include
MINDIR    = min
LIBDIR    = lib
LIBFILE   = humlib
TARGDIR   = bin
TOOLDIR   = cli
PUGIXML   = pugixml
MIDIFILE  = midifile

PREFLAGS  = -Wall -Wsign-compare
PREFLAGS += -O3
PREFLAGS += -I$(MINDIR)
PREFLAGS += -I$(INCDIR) -I$(INCDIR)/pugixml -I$(INCDIR)/midifile
#PREFLAGS += -g
PREFLAGS += -std=c++17

ifeq ($(shell uname -s),Darwin)
  PREFLAGS += -Wshorten-64-to-32
  PREFLAGS += -Wsign-compare
endif

#PREFLAGS += -static

POSTFLAGS = -L$(LIBDIR) -l$(LIBFILE) -l$(PUGIXML) -l$(MIDIFILE)

COMPILER = LANG=C $(ENV) g++ $(ARCH)
#COMPILER = clang++
#PREFLAGS += -stdlib=libc++

#                                                                         #
# End of user-modifiable variables.                                       #
#                                                                         #
###########################################################################


# Search paths for source and header prerequisites.
vpath %.h   $(INCDIR) $(INCDIR)/midifile
vpath %.cpp $(wildcard tests/test-*) examples myprograms
vpath %.cpp $(wildcard $(TOOLDIR)) examples myprograms

# Programs compiled by the default target.
PROGS1 = $(notdir $(patsubst %.cpp,%,$(wildcard $(TOOLDIR)/*.cpp)))
PROGS  = $(PROGS1) testgrid

# The actual archive file is the shared prerequisite. Unlike the old
# phony "library" prerequisite, GNU make builds this target at most once,
# then releases all program link commands to run in parallel.
LIBTARGET = $(LIBDIR)/lib$(LIBFILE).a

.PHONY: all examples info


###########################################################################
#                                                                         #
# Main targets                                                            #
#                                                                         #

examples: all

all: $(PROGS)
	@echo Finished compiling all programs: $(PROGS).

info:
	@echo "Programs to compile: $(PROGS)" | fmt

# Build the library only when the actual archive is absent.
# The leading '+' preserves GNU make's jobserver for the recursive make.
$(LIBTARGET):
	+$(MAKE) library

# Create the output directory once. This is an order-only prerequisite,
# so the directory timestamp never forces programs to relink.
$(TARGDIR):
	@mkdir -p $(TARGDIR)

# Every known program waits for the single completed library archive and
# the output directory. The suffix rule below performs the link.
$(PROGS): $(LIBTARGET) | $(TARGDIR)


###########################################################################
#                                                                         #
# Compile/link a program from its matching .cpp source.                   #
#                                                                         #

.cpp:
	@echo [CC] $@
	@$(COMPILER) $(PREFLAGS) -o $(TARGDIR)/$@ $< $(POSTFLAGS)

###########################################################################
