#
# Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
# Creation Date: Sun Feb  8 21:39:37 PST 2015
# Last Modified: Sun Feb  8 21:39:40 PST 2015
# Filename:      scorelib/class/Makefile.class
# Syntax:        GNU Makefile
#
# Description:   Fill in the source code line ranges from the current
#                version of the scorelib source code on GitHub.
#

BINDIR = ../bin

CLASS = $(shell basename `pwd`);

all:
	@echo
	@echo "make lines -- insert source code lines.";
	@echo "make aton  -- create ATON files for public functions.";
	@echo

lines:
	$(BINDIR)/insertCodeLines *.aton

aton:
	-rm *.aton
	$(BINDIR)/code2aton $(CLASS)

