#
# Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
# Creation Date: Sun Jan 25 05:59:18 PST 2015
# Last Modified: Wed Jan 28 22:15:40 PST 2015
# Filename:      scorelib/_includes/docslot/Makefile
# Syntax:        GNU Makefile
#
# Description:   Fill in short descriptions of functions in index files.
#

all: fix

fix:
	./fixcontent [A-Z]*.html

convert:
	./fixcontent Convert.html

files:
	cp -f ../../class/Convert/docslot.html			Convert.html
	cp -f ../../class/HumAddress/docslot.html		HumAddress.html
	cp -f ../../class/HumHash/docslot.html			HumHash.html
	cp -f ../../class/HumNum/docslot.html			HumNum.html
	cp -f ../../class/HumdrumFile/docslot.html		HumdrumFile.html
	cp -f ../../class/HumdrumFileBase/docslot.html		HumdrumFileBase.html
	cp -f ../../class/HumdrumFileContent/docslot.html	HumdrumFileContent.html
	cp -f ../../class/HumdrumFileStructure/docslot.html	HumdrumFileStructure.html
	cp -f ../../class/HumdrumLine/docslot.html		HumdrumLine.html
	cp -f ../../class/HumdrumToken/docslot.html		HumdrumToken.html




